# Generated by Django 6.0 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Полное имя автора (максимум 100 символов)', max_length=100, verbose_name='Автор')),
                ('bio', models.TextField(blank=True, default='', help_text='Краткая биография автора', verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Авторы',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='blogapp_aut_name_e69849_idx')],
            },
        ),
    ]
