# Generated by Django 6.0 on 2026-01-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Заголовок статьи', max_length=200, verbose_name='Заголовок статьи')),
                ('content', models.TextField(blank=True, default='', help_text='Контент статьи', verbose_name='Контент')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_articles', to='blogapp.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_articles', to='blogapp.category')),
                ('tags', models.ManyToManyField(related_name='articles', to='blogapp.tag')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-pub_date', 'title', 'pk'],
                'indexes': [models.Index(fields=['title', 'pub_date'], name='blogapp_art_title_87887c_idx')],
            },
        ),
    ]
